language: bash
os: windows
env:
  - WIXBIN="c:/Program Files (x86)/WiX Toolset v3.11/bin"
install:
  - cat .travis.yml
  - powershell Install-WindowsFeature Net-Framework-Core
  - choco install wixtoolset --version 3.11.1 -y
  - curl -o wintun-amd64-0.6.msm https://www.wintun.net/builds/wintun-amd64-0.6.msm
  - curl -o wintun-x86-0.6.msm https://www.wintun.net/builds/wintun-x86-0.6.msm
script:
  - '"$WIXBIN/candle" amd64.wxs -out amd64.wixobj'
  - '"$WIXBIN/candle" x86.wxs -out x86.wixobj'
  - '"$WIXBIN/light" amd64.wixobj -out wintun-amd64-0.6.msi'
  - '"$WIXBIN/light" x86.wixobj -out wintun-x86-0.6.msi'
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  overwrite: true
  file:
    - wintun-amd64-0.6.msi
    - wintun-x86-0.6.msi'
  skip_cleanup: true
  on:
    tags: true
