language: bash
os: windows
install:
  - powershell Install-WindowsFeature Net-Framework-Core
  - choco install wixtoolset -y
  - curl -o wintun-amd64-0.6.msm https://www.wintun.net/builds/wintun-amd64-0.6.msm
  - curl -o wintun-x86-0.6.msm https://www.wintun.net/builds/wintun-x86-0.6.msm
script:
  - candle.exe amd64.wxs -out amd64.wixobj
  - candle.exe x86.wxs -out x86.wixobj
  - light.exe amd64.wixobj -out amd64.msi
  - light.exe x86.wixobj -out x86.msi
